examples/basic_agent.py
examples/operator_agent.py
examples/testing.py
src/agentic/actor_agents.py
src/agentic/cli.py
src/agentic/events.py
src/agentic/runner.py
src/agentic/tools/browser_use.py
src/agentic/tools/unit_test_tool.py

This PR introduces an internal Queue when running agent requests. This allows the caller to stop listening for events for a while, while the agent continues. The next time you call `get_events(request_id)` then you will receive the events published in the meantime.
In the runner REPL we use this so you can "ctrl-c" a long task, and it will spawn a thread to keep reading events from the agent and echo them in gray to the terminal. Meanwhile you get a new prompt and can send another request:
this isn't really great in the REPL. But it should be better with a real web UI.
You can get the same thing with the REST API:
POST /process?request
<-- request_id
GET /get_events?request_id
<-- streams events

Support parallel agent requests

---

.gitignore
docs/REST_API.md
src/agentic/actor_agents.py

With the `_discovery` endpoint a client can discover all the running agents and their subpaths. From this it can build chooser menu, or can auto-discover the current single running agent.

added /_discovery REST endpoint

---

pyproject.toml
src/agentic/actor_agents.py
src/agentic/db/db_manager.py
src/agentic/db/models.py
src/agentic/run_manager.py
src/agentic/tools/github_tool.py
src/agentic/utils/sqlite.py
tests/test_run_logging_core.py
tests/test_run_logging_integration.py

Resolves #7 
- Added Run and RunLog db models that live inside a sqlite db
- Added a flag `enable_run_logs` that is default true that logs runs and their logs to the db
- Added `handle_event` to the `ActorBaseAgent` to be run before each event is yielded in `handlePromptOrResume`
- Added a `db_manager` which has basic CRUD operations for runs and run_logs
- Added a `run_manager` that has the `handle_event` callback declared inside it and adds the handler based on if `enable_run_logs` is enabled

Add runs and run_logs models in a sqlite db

---

.gitignore
src/agentic/actor_agents.py
src/agentic/db/db_manager.py
src/agentic/run_manager.py
src/agentic/ui/next-js/components.json
src/agentic/ui/next-js/next-env.d.ts
src/agentic/ui/next-js/next.config.js
src/agentic/ui/next-js/package-lock.json
src/agentic/ui/next-js/package.json
src/agentic/ui/next-js/postcss.config.js
src/agentic/ui/next-js/src/app/components/AgentChat.tsx
src/agentic/ui/next-js/src/app/components/RunsTable.tsx
src/agentic/ui/next-js/src/app/components/ui/alert.tsx
src/agentic/ui/next-js/src/app/components/ui/avatar.tsx
src/agentic/ui/next-js/src/app/components/ui/button.tsx
src/agentic/ui/next-js/src/app/components/ui/card.tsx
src/agentic/ui/next-js/src/app/components/ui/scroll-area.tsx
src/agentic/ui/next-js/src/app/components/ui/select.tsx
src/agentic/ui/next-js/src/app/components/ui/sheet.tsx
src/agentic/ui/next-js/src/app/components/ui/textarea.tsx
src/agentic/ui/next-js/src/app/globals.css
src/agentic/ui/next-js/src/app/layout.tsx
src/agentic/ui/next-js/src/app/lib/api.ts
src/agentic/ui/next-js/src/app/lib/utils.ts
src/agentic/ui/next-js/src/app/page.tsx
src/agentic/ui/next-js/tailwind.config.js
src/agentic/ui/next-js/tsconfig.json
src/agentic/utils/json.py
src/agentic/utils/sqlite.py

- Added a new directory at `src/agentic/ui/next-js` which contains a next.js app.
- It uses the shadcn library which is slim because it allows us to pick and choose which components to add, they are added via clii into `next-js/src/app/components/ui`
- Allow switching to previous runs, starting new chats
- Added API endpoints to get an agents runs and get a run's run_logs
- Made output from `/getevents` serializable
- To run the next js app first run `agentic serve examples/<agent_name>.py`. Then in the next-js folder run:
```
npm install
npm run dev
```
- Documentation both in the next-js directory and in the overall docs / README
- Add multi agent support for the runner
- Add voice mode
- Add background support
- Clicking a run in the runs table adds the logs to the correct run but it …

[Issue #40] Next.js UI

---

src/agentic/cli.py
src/agentic/utils/rag_helper.py

- Initialize Weaviate client with 'fatal' log level instead of 'error' (Cleans verbose)
- Ensure client is closed after indexing (that was causing port is already listening error)
- Update source_url to use absolute path for local files
- Add client initialization check in list_indexes function

Some small fixes for RAG

---

README.md
docs/DATA_MODEL.md
docs/RestApiTool.md
docs/ToolLibrary.md
docs/Tools.md
examples/oss_deep_research.py
src/agentic/actor_agents.py
src/agentic/events.py
src/agentic/swarm/types.py
src/agentic/tools/__init__.py
src/agentic/tools/rest_tool_v2.py
src/agentic/tools/unit_test_tool.py
tests/test_tool_logging.py

Logging inside tool function is very important. This PR adds support for a couple different approaches. The first is to use yield, but then you tool function becomes a generator:
```
def tool_func():
yield ToolOutput("something happened")
yield ToolOutput("something else")
..
yield "final result"
```
This may feel weird, so you can also do this instead:
```
def tool_func(run_context):
run_context.log("log1")
run_context.log("log2")
..   
return "final result"
```
This works by having run_context queue the log events, and then they will get auto-published (before the tool result) when you function completes.
✅ added docs and tests

added support for logging from tools using either yield or by calling run_context methods

---

src/agentic/tools/browser_use.py

This PR enhances the BrowserUseTool to provide better support for different model providers and Litellm-style model paths.
Key Changes:
- Add unified model initialization that supports both Litellm and Langchain implementations
- Implement proper API key management for major providers (Gemini, OpenAI, Anthropic)
- Add fallback API key inference for other providers
- Fix duplicate browser instance initialization bug
The changes allow for more flexible model specification:
```python
model="gemini/gemini-2.0-flash"    # Litellm style
model="anthropic/claude-3.5-sonnet-latest"         # Litellm style
model="gemini-2.0-flash"           # Direct style
```
API keys are automatically managed through the agentic_secrets system, with explicit support for:
- GEMINI_API_KEY
- OPENAI_API_KEY
- …

feat(browser-use): add unified model initialization with Litellm support

---

tests/test_repl_commands.py

Added test suite for verifying all REPL dot commands (.agent, .debug, .help, .model, .tools, .functions, .reset, .run, .history) using pytest fixtures and mocked I/O streams to ensure command functionality and output validation. 
Closes #27

added unit test for repl system commands

---

docs/Debugging.md
docs/Internals.md
examples/basic_agent.py
examples/deep_research/oss_deep_research.py
src/agentic/actor_agents.py
src/agentic/cli.py
src/agentic/common.py
src/agentic/db/db_manager.py
src/agentic/events.py
src/agentic/ray_mock.py
src/agentic/run_manager.py
src/agentic/runner.py
src/agentic/settings.py
src/agentic/tools/github_tool.py
src/agentic/tools/meeting_tool.py
src/agentic/utils/directory_management.py
tests/test_basics.py
tests/test_response_model.py
tests/test_run_logging_integration.py
tests/test_tool_logging.py
tests/test_tool_use.py

This PR does a few notable things:
- Renames "AgentFacade" to "AgentProxy"
- Introduces a new proxy base class, `BaseAgentProxy`. This class manages the underlying real agent instance (the ActorBaseAgent).
- BaseAgentProxy maintains a set of real agents in case multiple parallel requests are processed. The `_agent` attribute is used to keep the "default" instance used in the absence of parallel requests.
- Adds a new class `LocalAgentProxy` which uses agent instances directly instead of running them on Ray. This class is enabled by default.
- The code for managing multiple (parallel) requests is moved out of ActorBaseAgent and into the proxy class instead so that AgentBaseAgent can be simpler and just use normal `self` attributes for state.

A very big refactor to introduce Threaded agents as the default instead of using Ray

---

pyproject.toml

Seperated RAG dependencies in `pyproject.toml`. Starting a process to decrease time to build GitHub Actions by refactoring unnecessary installs.

Separate RAG dependencies

---

src/agentic/actor_agents.py

This was misguided code that only returned a single result from a tool call. fixed now

yikes! breaking return list of results

---

src/agentic/actor_agents.py
src/agentic/events.py
src/agentic/utils/summarizer.py
src/agentic/utils/token_estimation.py
tests/test_context_window.py

First I catched ContextWindowExceededError and implemented logic but since ContextWindowExceededError is triggered once even if logic is handled correctly, this weird log was appearing in response: 
```
(Tool Builder pid=44351) 
(Tool Builder pid=44351) Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
(Tool Builder pid=44351) LiteLLM.Info: If you need to debug this error, use `litellm._turn_on_debug()'.
(Tool Builder pid=44351)
```
So, I decided to go with token count. When we approach to model's context size, logic is triggered.

History token management

---

src/agentic/actor_agents.py
src/agentic/api.py
src/agentic/events.py
src/agentic/runner.py
src/agentic/swarm/types.py
src/agentic/tools/github_tool.py
src/agentic/tools/oauth_tool.py
tests/test_oauth_tool.py

- Implemented `OauthFlowRequest` event
- Implemented `get_oauth_callback_url` to get OAuth callback URL for a tool
- Also implemented `get_oauth_auth_code`  `set_oauth_auth_code` `set_oauth_token` `get_oauth_token` methods to enable to save and get auth_code and token
- Implemented `handle_oauth_callback` to save the returned `auth_code`. 
- `handle_oauth_static_callback` contains the callback URL that is called. We use `handle_oauth_static_callback` since OAuth providers often require registering a fixed callback URL that doesn't change between different authorization requests. 
The `auth_code` passed from the OAuth providers is saved from `handle_oauth_callback` method using  `set_oauth_auth_code`. Then, tools can get the saved `auth_code` using `get_oauth_auth_code`.

Added oauth support for tools

---

src/agentic/actor_agents.py
src/agentic/tools/meeting_tool.py

- When executing async tool functions, properly check for existing event loop and create new one if needed, instead of always using asyncio.run(). This prevents issues when running in contexts that already have an event loop.
- Add explicit initialization of RAG-related attributes in __init__ of meeting_tool
- Ensure proper cleanup of Weaviate client in __del__ and __getstate__

Fix asyncio run error meeting tool

---

docs/interacting-with-agents/rest-api.md
src/agentic/actor_agents.py
src/agentic/api.py
src/agentic/runner.py

This PR adds a hook to the API to look for a JWT token in the Auth header. If the token is present then we invoke a caller-supplied callback to resolve the "user" from the header. Then we map API calls to different Agent instances based on the user.
The lookup for the agent instance by user happens only on /process, which records the active agent by the request_id. Then in get_events we just find the right instance by the request ID. This seems logical, and has the side effect that if your brower client is using EventSource to stream get_events, it doesn't need to pass the JWT header in the event stream (which apparently isn't supported!).
I also added logging support to the API server which attempts to be mostly compatible with AGENTIC_DEBUG settings like we use with the cli.

added support for multiple users mapped to agent instances in the API

---

MANIFEST.in
pyproject.toml
src/agentic/tools/duckduckgo.py
src/agentic/tools/example_tool.py
src/agentic/tools/podcast_tool.py
src/agentic/tools/rest_api_tool.py
tests/test_tools_init.py
tests/utils/tools_utils.py

- Fix duckduckgo tool imports
- Add init function to rest api tool
- Make sure init and get_tools functions are overridden by all tools
- Exclude pycache from package imports

Fix DuckDuckGo and RestApi tools, make sure tests catch failures

---

examples/deep_research/oss_deep_research.py
examples/march_madness.py
src/agentic/actor_agents.py
src/agentic/api.py
src/agentic/dashboard/src/app/hooks/useChat.tsx
src/agentic/run_manager.py

closes #86 
The run logging was not created with subagents in mind, therefore the code needed refactoring for agents such as the deep researcher to log and work correctly. 
Changes made:
- Refactored the main callback logic to `_next_turn` to allow overrides to `next_turn` functions which can create subagents and yield events from them. 
- The handle_event function in run_manager needed refactoring to make sure it is using the correct run_id by replacing the `current_run_id` by run_context.run_id (the agent that is calling the event)
- Some minor checks were needed. For example, chcecking that the agent name is the same as the agent calling the event to avoid duplicate logging and the event payload was being written as a dictionary so that is a temporary fix to correctly find the content …

Working run logs with subagents

---

examples/dynamic_tools_agent.py

This PR makes two improvements to the dynamic tools agent example to work:
1. Replaces the hardcoded string literal "openai/gpt-4o-mini" with the imported GPT_4O_MINI constant from agentic.models, improving maintainability and consistency
2. Removes the unused BrowserUseTool import to keep imports clean

refactor: dynamic tools agent example

---

src/agentic/utils/rag_helper.py

When I run `python examples/agentic_oracle.py`, I get a closed `weaviateclient` after processing the first file.
`weaviate.exceptions.WeaviateClosedClientError: The `WeaviateClient` is closed. Run `client.connect()` to (re)connect!`
Right now, I added a `client_created` flag to track whether we created the client within the function and close if only `client` is created within the `rag_index_file` function so that we don't have a closed connection when we are processing more than one files from RAGTool `__init__` method. With this pr, `agentic_oracle.py` runs successfully

fix agent_oracle close connection error

---

examples/march_madness.py

Fixed TypeError when accessing TeamList length by correctly accessing the teams attribute.
Changes:
- Modified `len(teams_list)` to `len(teams_list.teams)` to properly count the number of teams
- This fixes the AttributeError that occurred when trying to get the length of the TeamList object directly
The error occurred because TeamList is a Pydantic model containing a list of teams in its 'teams' attribute, and we need to access that attribute to get the actual count of teams.

Fixed TeamList length access in March Madness agent

---

docs/building-agents/advanced-custom-agents.md
examples/deep_research/oss_deep_research.py
src/agentic/actor_agents.py

This PR introduces corrections to the subagent logging to ensure subagent logs correctly appear in the event logs on the dashboard. The problem was that subagents were creating their own `run_id` and therefore were not being linked to the run and the parent agent.

Added Subagent Logging

---

docs/tools/tool-library/automatic-tools.md
src/agentic/tools/automatic_tools.py

- Adds comprehensive documentation for `AutomaticTools` in `docs/tools/tool-library/`
- Removes unused `universal_read_file` method from `AutomaticTools` since:
- It was trying to call a non-existent `RAGTool._universal_read_file` method
- It wasn't being used anywhere in the codebase
- Removes unused `show_connections_only` parameter from `get_tool_listing` method

Add AutomaticTools docs and remove unused `universal_read_file` method

---

src/agentic/actor_agents.py
src/agentic/runner.py

This simple PR allows someone to specify run_context data via a function that gets invoked every time, rather than simple static data. This is super useful for your agent to, for example, have access to data you want to load from a database each time:
```
def get_current_trips():
current_trips = session.query(Trip).all()
trip_list = "\n".join([f"{t.id}: {t.title} ({t.start_date} - {t.end_date})" for t in current_trips])
return trip_list
runner = AgentRunner(new_agent)
runner.repl_loop({"trip_id": trip.id, "current_trips": get_current_trips})
```
So supplying `current_trips` as a function means that the function gets invoked every time before the next turn.

Enable dynamic context data

---

src/agentic/actor_agents.py

This change adds a timeout parameter with default value to `get_events`. I am NOT 100% we need this, but I feel like i've been observing hangs in get_events in some testing. 
The default behavior sets timeout=None which should be equivalent to what we have now, so I think this change is low risk.

added a timeout for get_events

---

README.md
src/agentic/dashboard/setup.py

Issue with npm not being detected on Windows when attempted to setup the Supercog dashboard, even when they are properly installed and PATH is configured. Returns error "npm or node not detected".
in src/agentic/dashboard/setup.py, imported os library, then changed the subprocess command of "npm" to "npm.cmd" if the os.name is "nt" (windows) instead of "posix" (unix/linux/mac)
The reason this bug exists is because on Windows, command-line executables installed via npm (like npm, npx, etc.) are typically provided as .cmd files (e.g., npm.cmd) in the system PATH:
Windows does not natively recognize scripts without an extension as executable.
The .cmd extension tells the Windows shell to run the file as a command script.
On Unix-like systems (Linux/macOS), the executable is just npm (no …

Fix for issue with Windows dashboard setup not detecting npm 

---

README.md

Fixed a few minor grammatical errors in the README.md file.

Fix grammatical errors in README

---

src/agentic/actor_agents.py
src/agentic/thread_manager.py

`PromptStarted` events were getting logged like this: `{"content": {"content": "actual prompt"}} which was surfaced with Scott's recent changes to loading chat history into the state. This addresses that and also allows for logs to be viewed even if the bug affects them.

Fix double content bug in thread logging

---

examples/geolocation_agent.py
pyproject.toml
src/agentic/tools/__init__.py
src/agentic/tools/__init__.pyi
src/agentic/tools/geolocation_tool.py
tests/test_geolocation_tool.py

Adds a geolocation tool with the following capabilities:
- Time: uses python's datetime library to get current time on the local machine.
- Timezone: uses python's tzlocal library to get the timezone of the local machine.
- Location: uses requests library to get ip of local machine, ip is then used in another request, which returns the following information:
1. city
2. region
3. country
4. coordinates (longitude/latitude) --> not the exact location of user, but the isp location.
5. timezone
6.  public ip
7. service provider
Note: gets geolocation information based on public ip of the machine it is being run on, meaning inaccuracies can occur if agent is being run by a server or if ip points to a different location (such as if a vpn is being used).
Other addition:   
Very basic agent also …

Geolocation Tool and Example Agent
