docs/index.md

Replaces "sensisible" with "sensible"

Fixes typo in index.md

---

.env.example
README.md
tests/test_ragtool.py

Add API Key Configuration and Improve File Path Handling in Tests  
This PR introduces the following enhancements and fixes:  
1. **API Key Configuration:**
- Added a `.env.example` file with placeholders for `OPENAI_API_KEY` and `ANTHROPIC_API_KEY` to guide users in setting up their environment variables.
- Updated the `README.md` with instructions on configuring API keys for LLM providers.
2. **Test Improvements:**
- Updated `tests/test_ragtool.py` to use `os.path.join` for constructing file paths dynamically, ensuring compatibility across different environments.
These changes improve usability by simplifying API key setup and making the test suite more robust and platform-independent.

Add API Key Configuration and Improve File Path Handling in Tests

---

pyproject.toml
src/agentic/cli.py
src/agentic/utils/file_reader.py
src/agentic/utils/fingerprint.py
src/agentic/utils/rag_helper.py
src/agentic/utils/summarizer.py
uv.lock

- Added semantic document indexing with Weaviate vector database integration
- Implemented intelligent text chunking and embedding generation pipeline
- Added universal file reader supporting multiple formats (PDF, CSV, JSON, etc.) and URLs
- Added document fingerprinting to detect duplicates and handle versioning
- Added metadata in indexing
- Added LLM-based document summarization capability
**TODO**

RAG Implementation | WIP

---

src/agentic/utils/rag_helper.py
tests/test_rag_operations.py

Unit test for RAG operations

---

README.md
examples/people_researcher.py
pyproject.toml
src/agentic/__init__.py
src/agentic/cli.py
src/agentic/tools/duckduckgo.py
tests/test_cli_load_time.py

Also made sure the CLI is still loading quickly

Changed our published package name

---

src/agentic/actor_agents.py
src/agentic/run_manager.py
src/agentic/swarm/types.py

Implement fix for issue: #38
I have this new pr instead of #45 because rebasing for #45 introduced changes on my already existing change
I will be closing #45

Tool webhook support fix

---

examples/agentic_oracle.py
examples/learning/rag_agent.py
src/agentic/__init__.py
src/agentic/actor_agents.py
src/agentic/cli.py
src/agentic/events.py
src/agentic/quiet_warnings.py
src/agentic/tools/rag_tool.py
src/agentic/utils/file_reader.py
src/agentic/utils/rag_helper.py

Various little rag fixes.
Made RAGTool functions basically just work on the default index.
Added logic to add files to index in the RAGTool constructor.

Created a RAG Agent from the agentic docs. 

---

src/agentic/actor_agents.py
src/agentic/events.py
src/agentic/runner.py
src/agentic/ui/next-js/package-lock.json
src/agentic/ui/next-js/package.json
src/agentic/ui/next-js/src/app/components/AgentChat.tsx
src/agentic/ui/next-js/src/app/components/AgentSidebar.tsx
src/agentic/ui/next-js/src/app/components/BackgroundTasks.tsx
src/agentic/ui/next-js/src/app/components/EventLogs.tsx
src/agentic/ui/next-js/src/app/components/MarkdownRenderer.tsx
src/agentic/ui/next-js/src/app/components/RunsTable.tsx
src/agentic/ui/next-js/src/app/components/ui/accordion.tsx
src/agentic/ui/next-js/src/app/components/ui/dropdown-menu.tsx
src/agentic/ui/next-js/src/app/lib/api.ts
src/agentic/ui/next-js/src/app/page.tsx
src/agentic/ui/next-js/tailwind.config.ts
tests/test_basics.py
tests/test_tool_use.py

This has the following working:
- Concurrent agent prompts, you can ask the same agent multiple things at once and they will work in separate threads
- UI For Background tasks
- UI for event logging

Add background task capability

---

src/agentic/actor_agents.py
tests/test_token_usage.py

Closes #29 
I am not unit test expert, unit test is coded by AI but seems logical.

Litellm usage counting and unit test

---

examples/airbnb_calendar_agent.py
examples/oss_operator.py
src/agentic/tools/airbnb_calendar_tool.py

A tool that can read and process an ical calendar from your airbnb listing.
Also found that oss_operator agent wasn't working with gemini so switched to openai and left gemini as a comment.

Airbnb tool and sample agent

---

docs/EVENTS.md
examples/learning/debugger.py
examples/oss_deep_research.prompts.yaml
examples/oss_deep_research.py
src/agentic/actor_agents.py
src/agentic/runner.py
src/agentic/swarm/util.py
src/agentic/tools/tavily_search_tool.py
tests/test_basics.py
tests/test_callbacks.py
tests/test_run_logging_integration.py

* Event depths should be tagged properly now. This relies on keeping the current depth in Thread local storage, which I don't love. But means that the caller doesn't have to track it.
* Implemented Human In the Loop logic for the Researcher to gather feedback on the report plan
* Refined the report prompts a bit, including parameterizing the number of web queries.

More Deep Research improvements

---

examples/oss_deep_research.py
src/agentic/ui/next-js/.eslintrc.json
src/agentic/ui/next-js/package-lock.json
src/agentic/ui/next-js/package.json
src/agentic/ui/next-js/src/app/components/AgentChat.tsx
src/agentic/ui/next-js/src/app/components/AgentSidebar.tsx
src/agentic/ui/next-js/src/app/components/BackgroundTasks.tsx
src/agentic/ui/next-js/src/app/components/EventLogs.tsx
src/agentic/ui/next-js/src/app/components/MarkdownRenderer.tsx
src/agentic/ui/next-js/src/app/components/RunsTable.tsx
src/agentic/ui/next-js/src/app/components/ui/accordion.tsx
src/agentic/ui/next-js/src/app/components/ui/alert.tsx
src/agentic/ui/next-js/src/app/components/ui/avatar.tsx
src/agentic/ui/next-js/src/app/components/ui/button.tsx
src/agentic/ui/next-js/src/app/components/ui/card.tsx
src/agentic/ui/next-js/src/app/components/ui/dropdown-menu.tsx
src/agentic/ui/next-js/src/app/components/ui/scroll-area.tsx
src/agentic/ui/next-js/src/app/components/ui/select.tsx
src/agentic/ui/next-js/src/app/components/ui/sheet.tsx
src/agentic/ui/next-js/src/app/components/ui/textarea.tsx
src/agentic/ui/next-js/src/app/hooks/useAgentData.tsx
src/agentic/ui/next-js/src/app/hooks/useChat.tsx
src/agentic/ui/next-js/src/app/layout.tsx
src/agentic/ui/next-js/src/app/lib/api.ts
src/agentic/ui/next-js/src/app/lib/utils.ts
src/agentic/ui/next-js/src/app/page.tsx
src/agentic/ui/next-js/src/app/providers/SWRProvider.tsx
src/agentic/ui/next-js/tsconfig.json
src/agentic/ui/next-js/types.d.ts

There is a lot in the weeds for next js best practices:
- Use hooks to maintain state across components
- Use SWR package to manage request caching
- Add types.d.ts to expose types across the application
- Consistent function calling and declaration
- Limit prop hammering
- Add eslint config
Also made some changes for the oss researcher, mainly just added a prompt started event so that the chat logs look right.
- Background task messages when processing (`Calling tool...`, `Analyzing result...`, etc)
- Add prompt buttons
- Human in the loop
- Send an event to background after it has started
- Background and foreground tasks are not running concurrently anymore
- Enable run logs from a custom next_turn function
- Update nouns

Next best practices, better chat output for multi-agent agents

---

src/agentic/actor_agents.py
src/agentic/custom_models/mock_provider.py
src/agentic/models.py
tests/test_mock_llm.py

Llm mocking for test purposes

---

examples/standup_agent.py
src/agentic/tools/github_tool.py
tests/test_github_tool.py

Started with a simple Github Analysis and agenda creation for a standup meeting. Works well with small and new repos but when it is run on a relatively established repo like agentic it runs into a ContextWindowExceededError due to too many tokens. 
Trying to work on minimizing the context window by only looking at a couple days history on Github.

Standup Agent Proposal

---

src/agentic/tools/github_tool.py
tests/test_github_tool.py

Added some documentation to the GithubTool class and its tests.

Minor documentation changes to the Github Tool

---

examples/basic_agent.py
src/agentic/actor_agents.py
src/agentic/dashboard/src/app/components/AgentChat.tsx
src/agentic/dashboard/types.d.ts
src/agentic/events.py

closes #82 
- Added prompt buttons and prompt handling in the backend
- Current frontend:

Added Prompt Buttons

---

examples/deep_research/oss_deep_research.py
examples/march_madness.py
src/agentic/actor_agents.py

Created an agent that can make a march madness prediction bracket. Also fixed some issues I created with the threaded agents rebase.
Bracket link: https://fantasy.espn.com/games/tournament-challenge-bracket-2025/bracket?id=e160eed0-0589-11f0-a450-2ffcabff716d

March madness agent and bug fixes

---

src/agentic/actor_agents.py
src/agentic/events.py
src/agentic/utils/summarizer.py
src/agentic/utils/token_estimation.py
tests/test_context_window.py

@drbrady8800 Merging this directly since previous PR already approved. Only added @pytest.mark.requires_llm for unit test.

Prompt st size handling

---

docs/rag-support.md
src/agentic/cli.py

Remove depreciated CLI commands | Update RAG readme

---

examples/meeting_notetaker.py
src/agentic/tools/meeting_tool.py

- added `Meeting_name_summary_and_attendees` to get structured output values
- added `check bot status` method
- added `_generate_meeting_summary`, `_fetch_meeting_data`, `clean_markdown` method
- now generating and saving summary to index in process_webhook method
- `get_meeting_info` method now search_collection

Small changes meetingbot

---

README.md
src/agentic/cli.py

- Add `--agent-path` option to streamlit cli command
- Add options to dashboard start and streamlit cli to run with ray and provide a backend port for the agentic api if booted
- Update the README with clearer instructions on how to interact with agents, better links to docs

Readme update

---

src/agentic/tools/browser_use.py

Ran into some issues trying to test out the oss operator, had to configure the docstring to tell the agent not to try to pass in a model.

Fix the browser use tool

---

examples/github.py
src/agentic/tools/github_tool.py

- used `GPT_4O_MINI` for `github.py` agent
- Filtered out pull requests issues in `get_github_issues` to only return actual github issues. We have `get_pull_requests` method to return pull requests list

Small fix GitHub agent

---

examples/news_demo.py

- removed unused `LinkedinDataTool()` declaration and it's method call `search_profiles` `get_profile` in `news_demo.py`

removed unused linkedindatatool declaration and it's method in news_demo.py

---

README.md

clarify setup instructions verified on Windows 10 WSL.

[doc] clarify uv venv setup instructions.

---

tests/test_linkedin_tool.py

- added test for linkedin_tool
You can run with `pytest tests/test_linkedin_tool.py -v`

added linkedin_tool test

---

docs/assets/swagger.json
docs/building-agents/advanced-custom-agents.md
docs/building-agents/custom-next_turn.md
mkdocs.yml

For more control and for implementing sub agents, you need to create your own next_turn function. However this needs some attention in order to make sure it works properly. This doc is intended to answer some of the questions developers may have about this.

Documentation for Customizing the next_turn functions in agents

---

examples/deep_research/oss_deep_research.py
src/agentic/actor_agents.py
src/agentic/dashboard/src/app/components/ChatInputForm.tsx
src/agentic/dashboard/src/app/hooks/useChat.tsx

Updated the agent to call PromptStarted/ResumeWithInput correctly. This led to some changes being needed in the frontend as it was developed with the previous implementation of the deep research agent in mind.

Updated Deep Research Agent

---

examples/oss_operator.py
pyproject.toml
src/agentic/tools/browser_use.py

This PR fixes an attribute error by replacing the direct litellm completion call with ChatLiteLLM from langchain_community. The change ensures proper callback handling for the browser agent.
Changes:
- Removed direct litellm completion usage
- Added ChatLiteLLM integration

fix: Switch to ChatLiteLLM for browser agent to resolve attribute error

---

deployment/Dockerfile.api
deployment/Dockerfile.dashboard
deployment/docker-entrypoint.sh
deployment/terraform/main.tf
deployment/terraform/modules/vpc/main.tf
deployment/terraform/modules/vpc/outputs.tf
deployment/terraform/modules/vpc/variables.tf
deployment/terraform/outputs.tf
deployment/terraform/terraform.tfvars.example
deployment/terraform/variables.tf
docs/assets/swagger.json
docs/deployment/index.md
src/agentic/cli.py
src/agentic/dashboard/.eslintrc.json
src/agentic/dashboard/next.config.js
src/agentic/dashboard/setup.py
src/agentic/dashboard/src/app/api/[...path]/route.ts
src/agentic/dashboard/src/app/lib/api.ts
src/agentic/utils/json.py
tests/cli/test_cli_dashboard.py

Updated the docker deployment scripts and files to have api or dashboard as an option. This way someone can deploy just the API or deploy the API and dashboard in the same container. Updated docs accordingly.

Docker deployments to AWS v2

---

examples/README.md

- added README.md to examples directory

add README.md to examples directory

---

pyproject.toml
src/agentic/swarm/types.py
src/agentic/utils/json.py

Pin openai

---

src/agentic/tools/automatic_tools.py
tests/test_automatic_tools.py

- Add explicit empty list return for no tool matches in `search_for_tool` method
- Add test fixtures for run context and toolset
- Add comprehensive test cases for tool search functionality
- Add tests for tool enabling and listing features
- Add edge case testing for various search scenarios

add automatic tools test cases

---

src/agentic/tools/mcp_tool.py

Fixed mcp tools' scheme representation.
@drbrady8800 The Sequential Thinking MCP tool does not trigger a chat_output event after the tool call is completed, which prevents the agent from generating a response. All other MCP tools work as expected. I’ll investigate further to understand why this is happening specifically with this tool.

MCP Tool Scheme Fix

---

src/agentic/cli.py
src/agentic/llm.py
src/agentic/models.py
tests/cli/test_cli_models.py

- Introduced new Gemini models: gemini-2.0-flash, gemini-2.5-pro-preview-05-06, and gemini-2.5-flash-preview-05-20.
- Added a CLI command for running completions with the default Gemini model.
- Updated model key handling to use GEMINI_API_KEY for Gemini models.
- Enhanced tests to validate the new Gemini command functionality.

Gemini 2.5

---

examples/basic_agent_reasoning.py
pyproject.toml
src/agentic/actor_agents.py
src/agentic/dashboard/src/app/components/EventLogs.tsx
src/agentic/dashboard/src/app/lib/api.ts
src/agentic/dashboard/types.d.ts
src/agentic/events.py
src/agentic/models.py

Reasoning works as expected. However, reasoning with tool only works with Gemini models due to litellm side problems. Claude supposed to support that but there is a known bug for that https://github.com/BerriAI/litellm/issues/11302: 
Closes #221 and #28

Add reasoning

---

docs/building-agents/agent-teams.md
examples/a2a_team_example.py
src/agentic/actor_agents.py
src/agentic/dashboard/src/app/components/EventLogs.tsx
src/agentic/dashboard/src/app/lib/api.ts
src/agentic/dashboard/types.d.ts
src/agentic/events.py
src/agentic/runner.py
src/agentic/tools/__init__.py
src/agentic/tools/__init__.pyi
src/agentic/tools/a2a_tool.py
tests/test_a2a_tool.py

Agent to Agent

---

examples/packing_list_agent.py

* Start by entering the place you are planning a trip to and the dates you want to go
* Answer the questions the agent asks you
* Finds the exact lon/lat of the place you give it for more accurate weather data
* Uses the weather tool to create a packing list geared for the weather
* Can deliver the list in either plain text or as a formatted PDF document
Requires installing fpdf2

Packing list generator agent
